### ISSUE TITLE
Intervals Stock start

### ISSUE THREAD

**Issue by SNokerYT** [divios/DailyShop#98]
you have been recently added a new amazing feature ( max stock ) is it possible to add another button also for ( sell option ) because for now, I know it's only working with the buy option.

**Comment by divios** [comment]
Hi!

Please check #90, is the next feature I want to add and I think you can achieve what you want with it. 

But come to think of it, in addition to the limit feature, I can add an option to the stock so that when the max stock is reached, players can't sell any more items, as if the shop's "storage" is full.

What do you think?

**Comment by mani1232** [comment]
I really need this feature!

> Hi!
> 
> Please check #90, is the next feature I want to add and I think you can achieve what you want with it.
> 
> But come to think of it, in addition to the limit feature, I can add an option to the stock so that when the max stock is reached, players can't sell any more items, as if the shop's "storage" is full.
> 
> What do you think?


I really need this feature!

**Comment by SNokerYT** [comment]
I'm with you with divios there also thing that gonna make it a massive feature 😂 if you could add to it ( interval number ) like the prices xD
